name: pptmaker
description: A sample command-line application with basic argument parsing.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.0

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  dart_pptx: ^0.1.3
  google_generative_ai: ^0.2.2
  prompts: ^2.0.0
  remove_markdown: ^0.0.2

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
